import { MenuItem, Order } from '@/types';

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: 'Jollof Rice',
    category: 'Rice',
    price: 6.99,
    description: 'Classic West African smoky tomato rice cooked with bell peppers and spices',
    image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&h=300&fit=crop',
    rating: 4.9,
    prepTime: '15 min',
    isPopular: true,
    isSpecial: true,
  },
  {
    id: 2,
    name: 'Egusi Soup & Fufu',
    category: 'Rice',
    price: 7.49,
    description: 'Rich melon seed soup with assorted meat served with smooth pounded yam',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop',
    rating: 4.8,
    prepTime: '10 min',
    isPopular: true,
  },
  {
    id: 3,
    name: 'Fried Rice & Chicken',
    category: 'Rice',
    price: 8.49,
    description: 'Seasoned fried rice with vegetables, served with crispy fried chicken',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop',
    rating: 4.7,
    prepTime: '15 min',
    isPopular: true,
  },
  {
    id: 4,
    name: 'Coconut Rice',
    category: 'Rice',
    price: 5.99,
    description: 'Fragrant rice cooked in creamy coconut milk with Kenyan spices',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop',
    rating: 4.5,
    prepTime: '12 min',
  },
  {
    id: 5,
    name: 'Suya Skewers',
    category: 'Grilled',
    price: 9.99,
    description: 'Spiced grilled beef skewers with groundnut spice blend, onions and tomatoes',
    image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop',
    rating: 4.9,
    prepTime: '20 min',
    isPopular: true,
    isSpecial: true,
  },
  {
    id: 6,
    name: 'Grilled Tilapia',
    category: 'Grilled',
    price: 11.99,
    description: 'Whole grilled tilapia marinated in African herbs, served with ugali',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',
    rating: 4.7,
    prepTime: '25 min',
  },
  {
    id: 7,
    name: 'BBQ Chicken',
    category: 'Grilled',
    price: 10.49,
    description: 'Half chicken marinated in smoky pepper marinade, grilled to perfection',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    rating: 4.6,
    prepTime: '20 min',
    isPopular: true,
  },
  {
    id: 8,
    name: 'Puff Puff',
    category: 'Snacks',
    price: 2.49,
    description: 'Fluffy deep-fried dough balls, lightly sweetened — a beloved West African snack',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&h=300&fit=crop',
    rating: 4.8,
    prepTime: '5 min',
    isPopular: true,
    discount: 20,
  },
  {
    id: 9,
    name: 'Akara (Bean Cakes)',
    category: 'Snacks',
    price: 3.49,
    description: 'Crispy fried bean fritters seasoned with peppers and onions',
    image: 'https://images.unsplash.com/photo-1593759608142-e976b059f4f4?w=400&h=300&fit=crop',
    rating: 4.5,
    prepTime: '8 min',
  },
  {
    id: 10,
    name: 'Chin Chin',
    category: 'Snacks',
    price: 1.99,
    description: 'Crunchy fried snack dough, lightly seasoned — perfect for studying sessions',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=300&fit=crop',
    rating: 4.4,
    prepTime: '3 min',
  },
  {
    id: 11,
    name: 'Plantain Chips',
    category: 'Snacks',
    price: 2.29,
    description: 'Thinly sliced and fried ripe plantains with a touch of sea salt',
    image: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=400&h=300&fit=crop',
    rating: 4.6,
    prepTime: '5 min',
  },
  {
    id: 12,
    name: 'Zobo (Hibiscus Drink)',
    category: 'Drinks',
    price: 1.99,
    description: 'Chilled hibiscus flower drink with ginger and a hint of citrus',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&h=300&fit=crop',
    rating: 4.8,
    prepTime: '2 min',
    isPopular: true,
  },
  {
    id: 13,
    name: 'Kunu (Millet Drink)',
    category: 'Drinks',
    price: 1.79,
    description: 'Refreshing fermented millet drink with spices — traditional and energizing',
    image: 'https://images.unsplash.com/photo-1606168094336-48f8b0851a97?w=400&h=300&fit=crop',
    rating: 4.5,
    prepTime: '2 min',
  },
  {
    id: 14,
    name: 'Tamarind Juice',
    category: 'Drinks',
    price: 2.19,
    description: 'Sweet-sour tamarind fruit drink, iced and refreshing for hot campus days',
    image: 'https://images.unsplash.com/photo-1587015990127-424b954571a7?w=400&h=300&fit=crop',
    rating: 4.6,
    prepTime: '2 min',
  },
  {
    id: 15,
    name: 'Mango Lassi',
    category: 'Drinks',
    price: 2.99,
    description: 'Creamy blended mango with yogurt and cardamom — a campus favourite',
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=300&fit=crop',
    rating: 4.7,
    prepTime: '3 min',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    studentName: 'Amara Diallo',
    studentId: 'STU-2024-0034',
    items: [
      { ...menuItems[0], quantity: 2 },
      { ...menuItems[11], quantity: 1 },
    ],
    pickupTime: '12:30',
    notes: 'Extra spicy please',
    total: 15.97,
    status: 'preparing',
    createdAt: new Date(),
  },
  {
    id: 'ORD-002',
    studentName: 'Kofi Mensah',
    studentId: 'STU-2024-0089',
    items: [
      { ...menuItems[4], quantity: 1 },
      { ...menuItems[7], quantity: 3 },
    ],
    pickupTime: '13:00',
    total: 17.46,
    status: 'ready',
    createdAt: new Date(),
  },
  {
    id: 'ORD-003',
    studentName: 'Fatima Hassan',
    studentId: 'STU-2024-0156',
    items: [
      { ...menuItems[2], quantity: 1 },
      { ...menuItems[13], quantity: 2 },
    ],
    pickupTime: '12:00',
    total: 12.87,
    status: 'completed',
    createdAt: new Date(),
  },
  {
    id: 'ORD-004',
    studentName: 'Emeka Okonkwo',
    studentId: 'STU-2024-0201',
    items: [
      { ...menuItems[1], quantity: 1 },
      { ...menuItems[10], quantity: 2 },
    ],
    pickupTime: '13:30',
    total: 12.07,
    status: 'received',
    createdAt: new Date(),
  },
  {
    id: 'ORD-005',
    studentName: 'Nia Osei',
    studentId: 'STU-2024-0312',
    items: [
      { ...menuItems[6], quantity: 1 },
      { ...menuItems[11], quantity: 2 },
    ],
    pickupTime: '12:45',
    total: 14.47,
    status: 'preparing',
    createdAt: new Date(),
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Amara Diallo',
    course: 'Computer Science, Year 3',
    text: 'The Jollof Rice here tastes just like home! Pre-ordering saves me so much time between lectures.',
    avatar: '👩🏾‍💻',
    rating: 5,
  },
  {
    id: 2,
    name: 'Kofi Mensah',
    course: 'Engineering, Year 2',
    text: 'Suya Skewers are unbeatable. The online order feature means I never wait in long queues anymore.',
    avatar: '👨🏿‍🔧',
    rating: 5,
  },
  {
    id: 3,
    name: 'Fatima Hassan',
    course: 'Medicine, Year 4',
    text: 'Quick, affordable, and so delicious. The daily specials keep me coming back every day!',
    avatar: '👩🏽‍⚕️',
    rating: 5,
  },
];

export const dailySpecials = {
  chefSpecial: menuItems[0],
  discountItem: menuItems[7],
};
